"""initial schema

Revision ID: 416497b5ec9c
Revises:
Create Date: 2026-08-25 12:48:37.922014
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "416497b5ec9c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_guilds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discord_guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_guilds")),
        sa.UniqueConstraint("discord_guild_id", name=op.f("uq_discord_guilds_discord_guild_id")),
    )
    op.create_table(
        "gear_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code",
            sa.Enum(
                "WEAPON",
                "OFFHAND",
                "HEAD",
                "BODY",
                "HANDS",
                "LEGS",
                "FEET",
                "EARRINGS",
                "NECKLACE",
                "BRACELETS",
                "RING_1",
                "RING_2",
                name="gearslotcode",
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=30), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gear_slots")),
        sa.UniqueConstraint("code", name=op.f("uq_gear_slots_code")),
        sa.UniqueConstraint("display_name", name=op.f("uq_gear_slots_display_name")),
        sa.UniqueConstraint("sort_order", name=op.f("uq_gear_slots_sort_order")),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_item_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("item_level", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("external_item_id", name=op.f("uq_items_external_item_id")),
        sa.UniqueConstraint("name", name=op.f("uq_items_name")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("abbreviation", name=op.f("uq_jobs_abbreviation")),
        sa.UniqueConstraint("name", name=op.f("uq_jobs_name")),
    )
    op.create_table(
        "raid_tiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raid_tiers")),
        sa.UniqueConstraint("code", name=op.f("uq_raid_tiers_code")),
    )
    op.create_table(
        "augmentation_material_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raid_tier_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_augmentation_material_types_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["raid_tier_id"],
            ["raid_tiers.id"],
            name=op.f("fk_augmentation_material_types_raid_tier_id_raid_tiers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_augmentation_material_types")),
        sa.UniqueConstraint(
            "raid_tier_id", "code", name=op.f("uq_augmentation_material_types_raid_tier_id")
        ),
    )
    op.create_table(
        "bis_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("raid_tier_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("gcd_label", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_bis_sets_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["raid_tier_id"], ["raid_tiers.id"], name=op.f("fk_bis_sets_raid_tier_id_raid_tiers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bis_sets")),
        sa.UniqueConstraint("job_id", "raid_tier_id", "name", name=op.f("uq_bis_sets_job_id")),
    )
    op.create_table(
        "loot_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raid_tier_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "GEAR", "COFFER", "AUGMENTATION_MATERIAL", "MOUNT", "OTHER", name="lootcategory"
            ),
            nullable=False,
        ),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_loot_types_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["raid_tier_id"], ["raid_tiers.id"], name=op.f("fk_loot_types_raid_tier_id_raid_tiers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loot_types")),
        sa.UniqueConstraint("raid_tier_id", "code", name=op.f("uq_loot_types_raid_tier_id")),
    )
    op.create_table(
        "raid_floors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raid_tier_id", sa.Integer(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.CheckConstraint("floor_number > 0", name=op.f("ck_raid_floors_positive_floor_number")),
        sa.ForeignKeyConstraint(
            ["raid_tier_id"], ["raid_tiers.id"], name=op.f("fk_raid_floors_raid_tier_id_raid_tiers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raid_floors")),
        sa.UniqueConstraint("id", "raid_tier_id", name=op.f("uq_raid_floors_id")),
        sa.UniqueConstraint(
            "raid_tier_id", "floor_number", name=op.f("uq_raid_floors_raid_tier_id")
        ),
    )
    op.create_table(
        "statics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["discord_guilds.id"], name=op.f("fk_statics_guild_id_discord_guilds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statics")),
        sa.UniqueConstraint("guild_id", "name", name=op.f("uq_statics_guild_id")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("static_id", sa.Integer(), nullable=True),
        sa.Column("actor_discord_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["static_id"], ["statics.id"], name=op.f("fk_audit_logs_static_id_statics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "bis_set_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bis_set_id", sa.Integer(), nullable=False),
        sa.Column("gear_slot_id", sa.Integer(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "SAVAGE",
                "AUGMENTED_TOME",
                "TOME",
                "CRAFTED",
                "CATCHUP",
                "RELIC",
                "NORMAL_RAID",
                "EITHER",
                "OTHER",
                "NOT_APPLICABLE",
                name="gearclassification",
            ),
            nullable=False,
        ),
        sa.Column("desired_item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bis_set_id"], ["bis_sets.id"], name=op.f("fk_bis_set_items_bis_set_id_bis_sets")
        ),
        sa.ForeignKeyConstraint(
            ["desired_item_id"], ["items.id"], name=op.f("fk_bis_set_items_desired_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["gear_slot_id"],
            ["gear_slots.id"],
            name=op.f("fk_bis_set_items_gear_slot_id_gear_slots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bis_set_items")),
        sa.UniqueConstraint("bis_set_id", "gear_slot_id", name=op.f("uq_bis_set_items_bis_set_id")),
    )
    op.create_table(
        "floor_loot_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raid_floor_id", sa.Integer(), nullable=False),
        sa.Column("loot_type_id", sa.Integer(), nullable=False),
        sa.Column("expected_quantity", sa.Integer(), nullable=False),
        sa.Column("book_cost", sa.Integer(), nullable=True),
        sa.Column("augmentation_material_type_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "book_cost IS NULL OR book_cost >= 0",
            name=op.f("ck_floor_loot_rules_nonnegative_book_cost"),
        ),
        sa.CheckConstraint(
            "expected_quantity >= 0", name=op.f("ck_floor_loot_rules_nonnegative_expected_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["augmentation_material_type_id"],
            ["augmentation_material_types.id"],
            name=op.f(
                "fk_floor_loot_rules_augmentation_material_type_id_augmentation_material_types"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["loot_type_id"],
            ["loot_types.id"],
            name=op.f("fk_floor_loot_rules_loot_type_id_loot_types"),
        ),
        sa.ForeignKeyConstraint(
            ["raid_floor_id"],
            ["raid_floors.id"],
            name=op.f("fk_floor_loot_rules_raid_floor_id_raid_floors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floor_loot_rules")),
        sa.UniqueConstraint(
            "raid_floor_id", "loot_type_id", name=op.f("uq_floor_loot_rules_raid_floor_id")
        ),
    )
    op.create_table(
        "priority_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("static_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("character_kind", sa.Enum("MAIN", "ALT", name="characterkind"), nullable=True),
        sa.Column(
            "gear_classification",
            sa.Enum(
                "SAVAGE",
                "AUGMENTED_TOME",
                "TOME",
                "CRAFTED",
                "CATCHUP",
                "RELIC",
                "NORMAL_RAID",
                "EITHER",
                "OTHER",
                "NOT_APPLICABLE",
                name="gearclassification",
            ),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_priority_rules_nonnegative_priority")),
        sa.ForeignKeyConstraint(
            ["static_id"], ["statics.id"], name=op.f("fk_priority_rules_static_id_statics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_priority_rules")),
        sa.UniqueConstraint("static_id", "name", name=op.f("uq_priority_rules_static_id")),
    )
    op.create_table(
        "split_weeks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("static_id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["static_id"], ["statics.id"], name=op.f("fk_split_weeks_static_id_statics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_split_weeks")),
        sa.UniqueConstraint("static_id", "week_start", name=op.f("uq_split_weeks_static_id")),
    )
    op.create_table(
        "static_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("static_id", sa.Integer(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["static_id"], ["statics.id"], name=op.f("fk_static_members_static_id_statics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_static_members")),
        sa.UniqueConstraint(
            "static_id", "discord_user_id", name=op.f("uq_static_members_static_id")
        ),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("static_member_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("world", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.Enum("MAIN", "ALT", name="characterkind"), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_characters_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["static_member_id"],
            ["static_members.id"],
            name=op.f("fk_characters_static_member_id_static_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
        sa.UniqueConstraint("name", "world", name=op.f("uq_characters_name")),
    )
    op.create_table(
        "loot_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_week_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "ACTIVE", "COMPLETE", "CANCELLED", name="lootplanstate"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["split_week_id"],
            ["split_weeks.id"],
            name=op.f("fk_loot_plans_split_week_id_split_weeks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loot_plans")),
        sa.UniqueConstraint("split_week_id", "name", name=op.f("uq_loot_plans_split_week_id")),
    )
    op.create_table(
        "split_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_week_id", sa.Integer(), nullable=False),
        sa.Column("group_number", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "group_number IN (1, 2)", name=op.f("ck_split_groups_group_number_one_or_two")
        ),
        sa.ForeignKeyConstraint(
            ["split_week_id"],
            ["split_weeks.id"],
            name=op.f("fk_split_groups_split_week_id_split_weeks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_split_groups")),
        sa.UniqueConstraint("id", "split_week_id", name=op.f("uq_split_groups_id")),
        sa.UniqueConstraint(
            "split_week_id", "group_number", name=op.f("uq_split_groups_split_week_id")
        ),
    )
    op.create_table(
        "character_augmentation_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("augmentation_material_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_character_augmentation_inventory_nonnegative_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["augmentation_material_type_id"],
            ["augmentation_material_types.id"],
            name=op.f(
                "fk_character_augmentation_inventory_augmentation_material_type_id_augmentation_material_types"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_augmentation_inventory_character_id_characters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_augmentation_inventory")),
        sa.UniqueConstraint(
            "character_id",
            "augmentation_material_type_id",
            name=op.f("uq_character_augmentation_inventory_character_id"),
        ),
    )
    op.create_table(
        "character_floor_book_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("raid_floor_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_character_floor_book_balances_nonnegative_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_floor_book_balances_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["raid_floor_id"],
            ["raid_floors.id"],
            name=op.f("fk_character_floor_book_balances_raid_floor_id_raid_floors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_floor_book_balances")),
        sa.UniqueConstraint(
            "character_id",
            "raid_floor_id",
            name=op.f("uq_character_floor_book_balances_character_id"),
        ),
    )
    op.create_table(
        "character_gear_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("gear_slot_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_gear_slots_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["gear_slot_id"],
            ["gear_slots.id"],
            name=op.f("fk_character_gear_slots_gear_slot_id_gear_slots"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_character_gear_slots_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_gear_slots")),
        sa.UniqueConstraint(
            "character_id", "gear_slot_id", name=op.f("uq_character_gear_slots_character_id")
        ),
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_inventory_items_nonnegative_quantity")),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_inventory_items_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_inventory_items_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
        sa.UniqueConstraint(
            "character_id", "item_id", name=op.f("uq_inventory_items_character_id")
        ),
    )
    op.create_table(
        "loot_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loot_plan_id", sa.Integer(), nullable=False),
        sa.Column("raid_floor_id", sa.Integer(), nullable=False),
        sa.Column("loot_type_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PLANNED",
                "OFFERED",
                "ASSIGNED",
                "RECEIVED",
                "SKIPPED",
                "CANCELLED",
                name="lootassignmentstate",
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_loot_assignments_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_loot_assignments_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["loot_plan_id"],
            ["loot_plans.id"],
            name=op.f("fk_loot_assignments_loot_plan_id_loot_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["loot_type_id"],
            ["loot_types.id"],
            name=op.f("fk_loot_assignments_loot_type_id_loot_types"),
        ),
        sa.ForeignKeyConstraint(
            ["raid_floor_id"],
            ["raid_floors.id"],
            name=op.f("fk_loot_assignments_raid_floor_id_raid_floors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loot_assignments")),
    )
    op.create_table(
        "split_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_week_id", sa.Integer(), nullable=False),
        sa.Column("split_group_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_split_participants_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["split_group_id", "split_week_id"],
            ["split_groups.id", "split_groups.split_week_id"],
            name=op.f("fk_split_participants_split_group_id_split_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["split_week_id"],
            ["split_weeks.id"],
            name=op.f("fk_split_participants_split_week_id_split_weeks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_split_participants")),
        sa.UniqueConstraint(
            "split_group_id", "character_id", name=op.f("uq_split_participants_split_group_id")
        ),
        sa.UniqueConstraint(
            "split_week_id", "character_id", name=op.f("uq_split_participants_split_week_id")
        ),
    )
    op.create_table(
        "weekly_lockouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("raid_floor_id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("cleared", sa.Boolean(), nullable=False),
        sa.Column("loot_eligible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_weekly_lockouts_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["raid_floor_id"],
            ["raid_floors.id"],
            name=op.f("fk_weekly_lockouts_raid_floor_id_raid_floors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weekly_lockouts")),
        sa.UniqueConstraint(
            "character_id",
            "raid_floor_id",
            "week_start",
            name=op.f("uq_weekly_lockouts_character_id"),
        ),
    )
    op.create_table(
        "loot_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loot_assignment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_loot_receipts_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_loot_receipts_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["loot_assignment_id"],
            ["loot_assignments.id"],
            name=op.f("fk_loot_receipts_loot_assignment_id_loot_assignments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loot_receipts")),
        sa.UniqueConstraint("loot_assignment_id", name=op.f("uq_loot_receipts_loot_assignment_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("loot_receipts")
    op.drop_table("weekly_lockouts")
    op.drop_table("split_participants")
    op.drop_table("loot_assignments")
    op.drop_table("inventory_items")
    op.drop_table("character_gear_slots")
    op.drop_table("character_floor_book_balances")
    op.drop_table("character_augmentation_inventory")
    op.drop_table("split_groups")
    op.drop_table("loot_plans")
    op.drop_table("characters")
    op.drop_table("static_members")
    op.drop_table("split_weeks")
    op.drop_table("priority_rules")
    op.drop_table("floor_loot_rules")
    op.drop_table("bis_set_items")
    op.drop_table("audit_logs")
    op.drop_table("statics")
    op.drop_table("raid_floors")
    op.drop_table("loot_types")
    op.drop_table("bis_sets")
    op.drop_table("augmentation_material_types")
    op.drop_table("raid_tiers")
    op.drop_table("jobs")
    op.drop_table("items")
    op.drop_table("gear_slots")
    op.drop_table("discord_guilds")
    # ### end Alembic commands ###
